### ISSUE TITLE
TF Wait for transform throws an error

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tf_server#1]
related to #9d16843

        [k][~]
        $ rosservice call /tf/wait_for_transform "
        target_frame: 'map'
        fixed_frame: 'amigo/base_link'
        target_time:
          secs: 0
          nsecs: 0
        timeout:
          secs: 0
          nsecs: 0" 
          
        ERROR: service [/tf/wait_for_transform] responded with an error:         basic_string::_M_create

This error when I try to start a challenge:

        Traceback (most recent call last):
          File "/home/rein/ros/kinetic/system/src/r5cop_demo/src/challenge/amigo/challenge_amigo.py", line 52, in <module>
            robot_smach_states.util.startup(setup_statemachine, challenge_name="r5cop_demo_amigo")
          File "/home/rein/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 78, in startup
            outcome = executioner.execute()
          File "/home/rein/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 359, in execute
            container_outcome = self._update_once()
          File "/home/rein/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 250, in _update_once
            raise ex
        smach.exceptions.InvalidUserCodeError: Could not execute state 'INITIALIZE' of type '<robot_smach_states.utility.Initialize object at 0x7f6dc830df10>': Traceback (most recent call last):
          File "/home/rein/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
            self._remappings[self._current_label]))
          File "/home/rein/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/utility.py", line 39, in execute
            self.robot.base.get_location()
          File "/home/rein/ros/kinetic/system/src/robot_skills/src/robot_skills/base.py", line 205, in get_location
            return get_location(self._robot_name, self._tf_listener)
          File "/home/rein/ros/kinetic/system/src/robot_skills/src/robot_skills/base.py", line 250, in get_location
            tf_listener.waitForTransform("/map", "/" + robot_name + "/base_link", time, rospy.Duration(20.0))
          File "/home/rein/ros/kinetic/system/src/tf_server/src/tf_server/tf_client.py", line 69, in waitForTransform
            resp = self._srv_wait_for_transform(req)
          File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
            return self.call(*args, **kwds)
          File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
            raise ServiceException("transport error completing service call: %s"%(str(e)))
        ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

**Comment by reinzor** [comment]
I will revert your commit for now: 7565b01e1c5acc36b483983b43ee1d5962b9cfd5

**Comment by reinzor** [comment]
This happens at a service call:

> [ERROR] [1480494715.053115705]: Exception thrown while processing service call: std::bad_alloc
> [ERROR] [1480494762.041133814]: Exception thrown while processing service call: std::bad_alloc
> [ERROR] [1480494862.665059574]: Exception thrown while processing service call: basic_string::_M_create
> [tf_server-14] process has died [pid 4479, exit code -11, cmd /home/rein/ros/kinetic/system/devel/lib/tf_server/tf_server __name:=tf_server __log:=/home/rein/.ros/log/4b458460-b6d7-11e6-b4d1-a0a8cd88ac07/tf_server-14.log].
> log file: /home/rein/.ros/log/4b458460-b6d7-11e6-b4d1-a0a8cd88ac07/tf_server-14*.log
>

**Comment by reinzor** [comment]
closed by 1503bd484dbe6f53bfa4c69ae83c9354a21129d2
